version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Installing dependencies...
      - cd backend/elysia
      - curl -fsSL https://bun.sh/install | bash
      - export BUN_INSTALL="$HOME/.bun"
      - export PATH="$BUN_INSTALL/bin:$PATH"
      - bun --version
      - bun install
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the application...
      # Add any build commands if needed
      - echo Build completed on `date`
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifact...

artifacts:
  files:
    - '**/*'
  base-directory: backend/elysia
  discard-paths: no

cache:
  paths:
    - 'backend/elysia/node_modules/**/*'
